[package]
name = "sinr"
version = "0.1.0"
edition = "2021"

[features]
default = ["trace"]
trace = []
unsafe = []
prealloc = []

[dependencies]
bilge = "0.2.0"
gdt-cpus = "25.5.0"
parking_lot = "0.12.3"
petgraph = "0.7.1"
rmw_free_barrier = { version = "0.1.0", path = "rmw_free_barrier" }
