# TODO this might improve things
#[unstable]
# build-std = ["core", "alloc", "std"] # this might affect things.

[profile.release]
codegen-units = 1
lto = "fat"
debug = true
strip = false

[build]
rustflags = [
    "-C", "target-cpu=native",
]